name: Node Project CI

on:
  schedule:
    - cron: '0 3,7,9,12 * * *'
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          persist-credentials: false
          # otherwise, there would be errors pushing refs to the destination repository.
          fetch-depth: 0

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          echo "_PATH=./packages/reptile" >> "$GITHUB_ENV"

      - name: Start services
        working-directory: ${{env._PATH}}
        run: |
          docker-compose up -d

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          # 选择要使用的 pnpm 版本
          version: 7
          # 使用 pnpm 安装依赖
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # 选择要使用的 node 版本
          node-version: 16.14.2
          # 缓存 pnpm 依赖
          cache: pnpm

      - name: Run tests or build
        working-directory: ${{env._PATH}}
        env:
          EMAIL_ACCOUNT: ${{ secrets.EMAIL_ACCOUNT }}
          EMAIL_AUTHORIZATION_CODE: ${{ secrets.EMAIL_AUTHORIZATION_CODE }}
        run: |
          pnpm run start

      - name: Stop services
        working-directory: ${{env._PATH}}
        run: |
          docker-compose down

      - name: Check for changes
        run: |
          if git diff --quiet; then
            echo "No changes detected. Skipping subsequent tasks."
            echo "skip_tasks=true" >> "$GITHUB_ENV"
          else
            echo "skip_tasks=false" >> "$GITHUB_ENV"
          fi

      - name: Commit files
        if: env.skip_tasks != 'true'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Add changes"

      - name: Push changes
        if: env.skip_tasks != 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
