name: Node Project CI

on:
  schedule:
    - cron: '0 3,7,12 * * *'
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start services
        run: |
          docker-compose up -d

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.2

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Run tests or build
        run: |
          pnpm run start

      # - name: Commit and push changes
      #   uses: crazy-max/ghaction-git-push@v1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: master
      #     force: true

      - name: Stop services
        run: |
          docker-compose down
