name: Node Project CI

on:
  schedule:
    - cron: '0 3,7,12 * * *'
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start services
        run: |
          docker-compose up -d

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          # 选择要使用的 pnpm 版本
          version: 7
          # 使用 pnpm 安装依赖
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # 选择要使用的 node 版本
          node-version: 16.14.2
          # 缓存 pnpm 依赖
          cache: pnpm

      - name: Run tests or build
        env:
          EMAIL_ACCOUNT: ${{ secrets.EMAIL_ACCOUNT }}
          EMAIL_AUTHORIZATION_CODE: ${{ secrets.EMAIL_AUTHORIZATION_CODE }}
          MAILBOX: ${{ secrets.MAILBOX }}
          NODE_ENV: ${{ secrets.production }}
        run: |
          pnpm run start

      # - name: Commit and push changes
      #   uses: crazy-max/ghaction-git-push@v1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: master
      #     force: true

      - name: Stop services
        run: |
          docker-compose down
